on:
  workflow_call:
    inputs:
      region:
        required: false
        description: 'Region of the account to deploy into'
        type: string
        default: 'us-east-1'
      accountId:
        required: true
        description: 'Account id of the account being deployed into'
        type: string
      externalRoleId:
        required: true
        description: 'External role id of the role being used in the account being deployed into'
        type: string
      roleName:
        required: true
        description: 'The role name used by GitHub to deploy'
        type: string
        default: 'arcticleaf'
    secrets:
      AL_GITHUB_AWS_ACCESS_KEY_ID:
        required: true
      AL_GITHUB_AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  reusable_cdk_deploy:
    name: Deploy CDK to AWS account
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ inputs.accountId }}:role/${{ inputs.roleName }}
        aws-region: ${{ inputs.region }}
        aws-access-key-id: ${{ secrets.AL_GITHUB_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AL_GITHUB_AWS_SECRET_ACCESS_KEY }}
        role-external-id: ${{ inputs.externalRoleId }}
        role-duration-seconds: 1200
        role-session-name: GitHubAction - $GITHUB_REPOSITORY - $GITHUB_SHA
        role-skip-session-tagging: true

    - name: Install NPM
      run: 'sudo apt update -y && sudo apt install nodejs npm -y'

    - name: Install AWS CDK
      run: 'sudo npm install -g aws-cdk'

    - name: Install Node Modules
      run: npm install
      
    - name: CDK Synth
      run: cdk synth
    
    - name: CDK Deploy
      run: cdk deploy
