on:
  workflow_call:
    inputs:
      region:
        required: false
        description: 'Region of the account to deploy into'
        type: string
        default: 'us-east-1'
      environment:
        required: true
        description: 'The environment (prod, staging, etc.)'
        type: string
      accountId:
        required: true
        description: 'The AWS account ID'
        type: string
      projectName:
        required: true
        description: 'The name of the project'
        type: string
      clientShort:
        required: true
        description: 'Short name for client'
        type: string
      customStackParameters:
        required: false
        description: 'Additional stack specific environment variables'
        type: string
        default: ''
    secrets:
      AL_GITHUB_AWS_ACCESS_KEY_ID:
        required: true
      AL_GITHUB_AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_EXTERNAL_ID:
        required: true
      customStackParameters:
        required: false
        description: 'Additional secret stack specific environment variables'

jobs:
  cdk_deploy:
    name: CDK Synth & Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AL_GITHUB_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AL_GITHUB_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
          role-to-assume: arn:aws:iam::${{ inputs.accountId }}:role/arcticleaf/Deployment
          role-session-name: github-ci
          role-external-id: ${{ secrets.AWS_EXTERNAL_ID }}
          role-duration-seconds: 3599
          role-skip-session-tagging: true
      - name: Installing dependencies
        run: npm install
      - name: Synthesizing
        run: cdk synth
      - name: Building & Deploying
        run: >
          cdk deploy --strict
                     --outputs-file       cdk-outputs.json
                     --notification-arns  arn:aws:sns:${{ inputs.region }}:${{ inputs.accountId }}:CloudFormation-Notifications
                     --tags               ${{ inputs.clientShort }}:deploy:env=${{ inputs.environment }}
                     --progress           events
                     --region             ${{ inputs.region }}
                     --change-set-name    ${{ inputs.projectName }}-${{ inputs.environment }}
                     --context            Environment=${{ inputs.environment }} ${{ inputs.customStackParameters }} ${{ secrets.customStackParameters }}
                     --parameters         Environment=${{ inputs.environment }} ${{ inputs.customStackParameters }} ${{ secrets.customStackParameters }}
        
