on:
  workflow_call:
    inputs:
      region:
        required: false
        description: 'Region of the account to deploy into'
        type: string
        default: 'us-east-1'
      environment:
        required: true
        description: 'The environment (prod, staging, etc.)'
        type: string
      accountId:
        required: true
        description: 'The AWS account ID'
        type: string
      projectName:
        required: true
        description: 'The name of the project'
        type: string
      clientShort:
        required: true
        description: 'Short name for client'
        type: string
      s3Bucket:
        required: true
        description: 'S3 deploy bucket'
        type: string
      customStackParameters:
        required: false
        description: 'Additional stack specific environment variables'
        type: string
        default: ''
    secrets:
      AL_GITHUB_AWS_ACCESS_KEY_ID:
        required: true
      AL_GITHUB_AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_EXTERNAL_ID:
        required: true
      customStackParameters:
        required: false
        description: 'Additional secret stack specific environment variables'

jobs:
  sam_deploy:
    name: SAM Build & Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AL_GITHUB_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AL_GITHUB_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
          role-to-assume: arn:aws:iam::${{ inputs.accountId }}:role/arcticleaf/Deployment
          role-session-name: github-ci
          role-external-id: ${{ secrets.AWS_EXTERNAL_ID }}
          role-duration-seconds: 3599
          role-skip-session-tagging: true
      - name: Building SAM project
        run: sam build --use-container
      - name: Deploying SAM project
        run: |
          
          sam deploy --no-fail-on-empty-changeset --config-env ${{ inputs.environment }} --stack-name ${{ inputs.projectName }}-${{ inputs.environment }} --s3-prefix ${{ inputs.projectName }}-${{ inputs.environment }} --s3-bucket ${{ inputs.s3Bucket }} --region ${{ inputs.region }} --notification-arns arn:aws:sns:${{ inputs.region }}:${{ inputs.accountId }}:CloudFormation-Notifications --capabilities CAPABILITY_NAMED_IAM --config-file samconfig.toml --parameter-overrides Environment=${{ inputs.environment }} ${{ inputs.customStackParameters }} ${{ secrets.customStackParameters }} --tags ${{ inputs.clientShort }}:deploy:env=${{ inputs.environment }}
